#ifndef CONSTANTS_H
#define CONSTANTS_H

enum class_units {ROBOT, VEHICLE, OT_OBJECT};

enum units {GRUNT = 0, PSYCHO = 1, TOUGHT = 2, PYRO = 3, SNIPER = 4, LAZER = 5, 
JEEP = 6, MEDIUM_TANK = 7, LIGHT_TANK = 8, HEAVY_TANK = 9, MML = 10};

enum unit_speed { //veocidad (por seg ?)
		ROBOT_SPEED = 4, JEEP_SPEED = 8, MEDIUM_TANK_SPEED = 5, 
		LIGHT_TANK_SPEED = 6, HEAVY_TANK_SPEED = 5, MML_SPEED = 5
	};

enum base_health {GRUNT_HEALTH = 60, PSYCHO_HEALTH = 80, TOUGHT_HEALTH = 300, 
PYRO_HEALTH = 100, SNIPER_HEALTH = 80, LASER_HEALTH = 100, JEEP_HEALTH = 60, 
MEDIUM_TANK_HEALTH = 120, LIGHT_TANK_HEALTH = 80, HEAVY_TANK_HEALTH = 180, 
MML_HEALTH = 200};

enum weapon_damage {BALAS = 2, LANZALLAMAS = 10, PROYECTILES = 20, 
LASER = 10, MISILES = 25};

#define GRUNT_SF 2
#define PSYCHO_SF 10
#define TOUGHT_SF 2
#define PYRO_SF 4
#define SNIPER_SF 4
#define LASER_SF 4
#define JEEP_SF 6
#define MEDIUM_TANK_SF 0.5
#define LIGHT_TANK_SF 0.5
#define HEAVY_TANK_SF 0.5
#define MML_SFSF 2

enum range {GRUNT_RANGE = 7, PSYCHO_RANGE = 7, TOUGHT_RANGE = 5, 
PYRO_RANGE = 6, SNIPER_RANGE = 10, LASER_RANGE = 7, JEEP_RANGE = 6, 
MEDIUM_TANK_RANGE = 7, LIGHT_TANK_RANGE = 6, HEAVY_TANK_RANGE = 8, 
MML_RANGE = 8};

#endif