#ifndef CONSTANTS_H
#define CONSTANTS_H


int getClassCodeFromUnit(int unit_c);
int getSpeedFromUnit(int unit_c);
int getHealthFromUnit(int unit_c);

enum class_units {ROBOT = 20, VEHICLE = 21, BUILDING = 22};

enum units {GRUNT = 0, PSYCHO = 1, TOUGHT = 2, PYRO = 3, SNIPER = 4, LAZER = 5, 
	JEEP = 6, MEDIUM_TANK = 7, LIGHT_TANK = 8, HEAVY_TANK = 9, MML = 10, 
	FORT = 11, ROBOT_FACTORY = 12, VEHICLE_FACTORY = 13};

enum unit_speed { //veocidad (por seg ?)
		ROBOT_SPEED = 4, JEEP_SPEED = 8, MEDIUM_TANK_SPEED = 5, 
		LIGHT_TANK_SPEED = 6, HEAVY_TANK_SPEED = 5, MML_SPEED = 5 };

enum base_health {GRUNT_HEALTH = 60, PSYCHO_HEALTH = 80, TOUGHT_HEALTH = 300, 
PYRO_HEALTH = 100, SNIPER_HEALTH = 80, LASER_HEALTH = 100, JEEP_HEALTH = 60, 
MEDIUM_TANK_HEALTH = 120, LIGHT_TANK_HEALTH = 80, HEAVY_TANK_HEALTH = 180, 
MML_HEALTH = 200, BUILDING_HEALTH = 1000 };

enum weapon_damage {BALAS = 2, LANZALLAMAS = 10, PROYECTILES = 20, 
LASER = 10, MISILES = 25 };

enum fabrication_time { GRUNT_F_TIME = 575, PSYCHO_F_TIME = 600, 
TOUGHT_F_TIME = 742, PYRO_F_TIME = 840, SNIPER_F_TIME = 575, LAZER_F_TIME = 900,
JEEP_F_TIME = 660, MEDIUM_TANK_F_TIME = 1080, LIGHT_TANK_F_TIME = 840, 
HEAVY_TANK_F_TIME = 1200, MML_F_TIME = 1320 };

enum unit_tech_level { GRUNT_TL = 2, PSYCHO_TL = 2, 
TOUGHT_TL = 2, PYRO_TL = 4, SNIPER_TL = 3, LAZER_TL = 5,
JEEP_TL = 1, MEDIUM_TANK_TL = 3, LIGHT_TANK_TL = 2, 
HEAVY_TANK_TL = 4, MML_TL = 5 };


#define GRUNT_SF 2
#define PSYCHO_SF 10
#define TOUGHT_SF 2
#define PYRO_SF 4
#define SNIPER_SF 4
#define LASER_SF 4
#define JEEP_SF 6
#define MEDIUM_TANK_SF 0.5
#define LIGHT_TANK_SF 0.5
#define HEAVY_TANK_SF 0.5
#define MML_SFSF 2

enum range {GRUNT_RANGE = 7, PSYCHO_RANGE = 7, TOUGHT_RANGE = 5, 
PYRO_RANGE = 6, SNIPER_RANGE = 10, LASER_RANGE = 7, JEEP_RANGE = 6, 
MEDIUM_TANK_RANGE = 7, LIGHT_TANK_RANGE = 6, HEAVY_TANK_RANGE = 8, 
MML_RANGE = 8};

#endif

